### ISSUE TITLE
Adding linktree as a "useful link"

### ISSUE THREAD

**Issue by m-pitera** [acm-uiuc/core#103]
![image](https://user-images.githubusercontent.com/26448943/131928299-08686573-2ddb-4b9f-85ca-8577059224f0.png)

Adding a link to the linktree under Useful Links on the about page could be useful. Thoughts?

Linktree link: linktr.ee/acmuiuc

We could have the text be "ACM@UIUC Resources" or something like that

**Comment by csood2** [comment]
added
