### ISSUE TITLE
The corporate email on the sponsors page is invalid

### ISSUE THREAD

**Issue by m-pitera** [acm-uiuc/core#104]
![image](https://user-images.githubusercontent.com/26448943/131928469-f01f85cd-28c2-43af-8a21-38bf5ee4d584.png)

This email should be updated to 
![image](https://user-images.githubusercontent.com/26448943/131928506-ee6cd4c8-15f5-4f5d-821e-c32a41f6a131.png)

This is found on the sponsors page: http://acm.illinois.edu/sponsors

**Comment by csood2** [comment]
corrected
