### ISSUE TITLE
Why is Numerade at the bottom of the sponsors page? Are they a sponsor?

### ISSUE THREAD

**Issue by m-pitera** [acm-uiuc/core#105]
![image](https://user-images.githubusercontent.com/26448943/131928567-8fcb6c8f-4fbe-4876-8dae-936ce7271621.png)

This should be removed if not a current sponsor, otherwise please just close this issue lol.

Found on the sponsors page here: http://acm.illinois.edu/sponsors

**Comment by csood2** [comment]
They paid us to put it there until Feb 2022
