### ISSUE TITLE
Removing Old Committee Info in About Us Page

### ISSUE THREAD

**Issue by m-pitera** [acm-uiuc/core#98]
![image](https://user-images.githubusercontent.com/26448943/131713784-92539955-11fd-41e7-a6f8-efe364cba7cf.png)
![image](https://user-images.githubusercontent.com/26448943/131713821-9839d664-7f85-4f12-b39e-917e1a79a255.png)

Both of these are no longer relevant

![image](https://user-images.githubusercontent.com/26448943/131713854-a101e80f-dae2-4738-bc47-990d626edd5b.png)
These emails should be updated to: contact@reflectionsprojections.org

**Comment by csood2** [comment]
I'll do it by EOD tomorrow

**Comment by csood2** [comment]
Completed, pls close. Instead of removing Infra, changed text to "it could be you!"
